name: POI API

on:
  pull_request:
    branches: [ master ]
    paths: 
      - 'apis/poi/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.8
    - name: Install dependencies
      run: dotnet restore ./apis/poi/poi.sln
    - name: Build
      run: dotnet build  ./apis/poi/poi.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test  ./apis/poi/poi.sln --no-restore --verbosity normal
