name: POI API CD

on:
  push:
    branches: [ master ]
    paths:
      - 'apis/poi/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Authenticate to AZ CLI
    - name: Log in with Azure
        uses: azure/login@v1
        with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Variables
    - name: Setup variables
    - run: |
        $ACRNAME = 'openhack0gl551n4acr'
        $BASEIMAGETAG = ${{ github_sha }} 
    - working-directory: ./apis/poi/web
    - name: Azure CLI script
        uses: azure/CLI@v1
        with:
        azcliversion: 2.0.72
        inlineScript: |
            az acr build --image "devopsoh/api-poi:${BASEIMAGETAG}" --registry $ACRNAME --file Dockerfile .
 
  release:
    needs: build

    runs-on: ubuntu-latest

    steps:

    # Authenticate to AZ CLI
    - name: Log in with Azure
        uses: azure/login@v1
        with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy the image to App Service
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'api-poi'
        images: '${{ ACRNAME }}/api-poi:${{ BASEIMAGETAG }}'
    
    - name: Report a bug in AzDO
      uses: ./.github/actions/azuredevops-bug-action
      if: failure()
      with:
        OrganizationName: "OHTeam7"
        PAT: "PAT"
        ProjectName: "driving-app-team7"
        AreaPath: "driving-app-team7\\Automation"
        IterationPath: "driving-app-team7"
        GithubToken: "GithubToken"
        WorkflowFileName: "poi-api.yml"
      env:
        PAT: ${{ secrets.PAT}}
        GithubToken: ${{ secrets.githubtoken}}
