name: POI API

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'apis/poi/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore ./apis/poi/poi.sln
    - name: Build
      run: dotnet build  ./apis/poi/poi.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test  ./apis/poi/poi.sln --no-restore --verbosity normal
    - name: Report a bug in AzDO
      uses: ./.github/actions/azuredevops-bug-action
      if: failure()
      with:
        OrganizationName: "OHTeam7"
        PAT: "PAT"
        ProjectName: "driving-app-team7"
        AreaPath: "driving-app-team7\\Automation"
        IterationPath: "driving-app-team7"
        GithubToken: "GithubToken"
        WorkflowFileName: "poi-api.yml"
      env:
        PAT: ${{ secrets.PAT}}
        GithubToken: ${{ secrets.githubtoken}}
