name: Userprofile API CD

env: 
  staging_url: https://openhack0gl551n4userprofile-staging.azurewebsites.net/api/healthcheck/user
  production_url: https://openhack0gl551n4userprofile.azurewebsites.net/api/healthcheck/user

on:
  push:
    branches: [ master ]
    paths:
      - 'apis/userprofile/**'

  workflow_dispatch:
    branches: [ master ]
    paths:
      - 'apis/userprofile/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Authenticate to AZ CLI
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          cd './apis/userprofile'
          az acr build --image "devopsoh/api-userprofile:${GITHUB_SHA}" --registry 'openhack0gl551n4acr' --file Dockerfile .

    - name: Report a bug in AzDO
      uses: ./.github/actions/azuredevops-bug-action
      if: failure()
      with:
        OrganizationName: "OHTeam7"
        PAT: "PAT"
        ProjectName: "driving-app-team7"
        AreaPath: "driving-app-team7\\Automation"
        IterationPath: "driving-app-team7"
        GithubToken: "GithubToken"
        WorkflowFileName: "userprofile-api-cd.yml"
      env:
        PAT: ${{ secrets.PAT}}
        GithubToken: ${{ secrets.githubtoken}}


  deploy_stage:
    needs: build
    runs-on: ubuntu-latest

    steps:

    # Authenticate to AZ CLI
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy the image to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhack0gl551n4userprofile'
        slot-name: 'staging'
        images: 'openhack0gl551n4acr/api-userprofile:${{ github.sha }}'

    - name: Report a bug in AzDO
      uses: ./.github/actions/azuredevops-bug-action
      if: failure()
      with:
        OrganizationName: "OHTeam7"
        PAT: "PAT"
        ProjectName: "driving-app-team7"
        AreaPath: "driving-app-team7\\Automation"
        IterationPath: "driving-app-team7"
        GithubToken: "GithubToken"
        WorkflowFileName: "userprofile-api-cd.yml"
      env:
        PAT: ${{ secrets.PAT}}
        GithubToken: ${{ secrets.githubtoken}}

  validate_stage:
    needs: deploy_stage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run validation script
      run: /tools/polling.sh $staging_url

    - name: Report a bug in AzDO
      uses: ./.github/actions/azuredevops-bug-action
      if: failure()
      with:
        OrganizationName: "OHTeam7"
        PAT: "PAT"
        ProjectName: "driving-app-team7"
        AreaPath: "driving-app-team7\\Automation"
        IterationPath: "driving-app-team7"
        GithubToken: "GithubToken"
        WorkflowFileName: "userprofile-api-cd.yml"
      env:
        PAT: ${{ secrets.PAT}}
        GithubToken: ${{ secrets.githubtoken}}


  swap_slots:
    needs: validate_stage
    runs-on: ubuntu-latest

    steps:
    - name: Swap
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az webapp deployment slot swap -g openhack0gl551n4rg -n openhack0gl551n4userprofile --slot staging --target-slot production

    - name: Report a bug in AzDO
      uses: ./.github/actions/azuredevops-bug-action
      if: failure()
      with:
        OrganizationName: "OHTeam7"
        PAT: "PAT"
        ProjectName: "driving-app-team7"
        AreaPath: "driving-app-team7\\Automation"
        IterationPath: "driving-app-team7"
        GithubToken: "GithubToken"
        WorkflowFileName: "userprofile-api-cd.yml"
      env:
        PAT: ${{ secrets.PAT}}
        GithubToken: ${{ secrets.githubtoken}}


  validate_swap_prod:
    needs: swap_slots
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run validation script
      run: /tools/polling.sh $production_url

    - name: Swap
      if: ${{ failure() }}
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az webapp deployment slot swap -g openhack0gl551n4rg -n openhack0gl551n4userprofile --slot production --target-slot staging

    - name: Report a bug in AzDO
      uses: ./.github/actions/azuredevops-bug-action
      if: failure()
      with:
        OrganizationName: "OHTeam7"
        PAT: "PAT"
        ProjectName: "driving-app-team7"
        AreaPath: "driving-app-team7\\Automation"
        IterationPath: "driving-app-team7"
        GithubToken: "GithubToken"
        WorkflowFileName: "userprofile-api-cd.yml"
      env:
        PAT: ${{ secrets.PAT}}
        GithubToken: ${{ secrets.githubtoken}}